import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/page";
import Footer from "@/Components/Footer/Footer";
import AuthProvaider from "@/utils/AuthProvider";
import Navbar from "@/Components/Header/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Orange Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
